spring:
  application:
    name: seed4JSampleExtension
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com:
      seed4j:
        extension: INFO

jhlite:
  hidden-resources:
    # Disable the modules and its dependencies by slugs
    slugs: custom-jhlite
server:
  port: 8080
